@include('Admin.Layout.head')
@include('Admin.Layout.sidebar')
@include('Admin.Layout.header')
@include('Admin.Layout.index')
@include('Admin.Layout.footer')

@yield('head')
@yield('sidebar')
@yield('header')
@yield('content')
@yield('footer')
